[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fork_url = "${SEPOLIA_RPC_URL}"
fork_block_number = 5219068

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
